//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVehiculos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int Reservarid { get; set; }
        public System.DateTime FechaReserva { get; set; }
        public int Clienteid { get; set; }
        public int CentroRecogidaid { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public Nullable<int> CentroDevolucionid { get; set; }
        public Nullable<int> Vehiculoid { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> DepositoLleno { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Coches Coches { get; set; }
        public virtual Delegaciones DelegacionesEntrega { get; set; }
        public virtual Delegaciones DelegacionesRecogida { get; set; }
    }
}
